Update keys

diff --git a/.config/zsh/keys b/.config/zsh/keys
--- a/.config/zsh/keys
+++ b/.config/zsh/keys
@@ -2,41 +2,50 @@
 # vim: set ft=zsh :
 
 autoload zkbd
-function zkbd_file() {
-    [[ -f ~/.zkbd/${TERM}-${VENDOR}-${OSTYPE} ]] && printf '%s' ~/".zkbd/${TERM}-${VENDOR}-${OSTYPE}" && return 0
-    [[ -f ~/.zkbd/${TERM}-${DISPLAY}          ]] && printf '%s' ~/".zkbd/${TERM}-${DISPLAY}"          && return 0
-    return 1
-}
-
-[[ ! -d ~/.zkbd ]] && mkdir ~/.zkbd
-keyfile=$(zkbd_file)
-ret=$?
-if [[ ${ret} -ne 0 ]]; then
-    zkbd
-    keyfile=$(zkbd_file)
-    ret=$?
-fi
-if [[ ${ret} -eq 0 ]] ; then
-    source "${keyfile}"
+bindkey -e
+if [[ -f ${ZDOTDIR}/.zkbd/$TERM-${DISPLAY:-$VENDOR-$OSTYPE} ]]; then
+    source ${ZDOTDIR}/.zkbd/$TERM-${DISPLAY:-$VENDOR-$OSTYPE}
 else
-    printf 'Failed to setup keys using zkbd.\n'
+    print "Key file not found. Run zkbd to create.\n"
 fi
-unfunction zkbd_file; unset keyfile ret
 
-# setup key accordingly
-[[ -n "${key[Home]}"    ]]  && bindkey  "${key[Home]}"    beginning-of-line
-[[ -n "${key[End]}"     ]]  && bindkey  "${key[End]}"     end-of-line
-[[ -n "${key[Home]}"    ]]  && bindkey -M vicmd "${key[Home]}"    beginning-of-line
-[[ -n "${key[End]}"     ]]  && bindkey -M vicmd "${key[End]}"     end-of-line
-[[ -n "${key[Insert]}"  ]]  && bindkey  "${key[Insert]}"  overwrite-mode
-[[ -n "${key[Delete]}"  ]]  && bindkey  "${key[Delete]}"  delete-char
-[[ -n "${key[Up]}"      ]]  && bindkey  "${key[Up]}"      up-line-or-history
-[[ -n "${key[Down]}"    ]]  && bindkey  "${key[Down]}"    down-line-or-history
-[[ -n "${key[Left]}"    ]]  && bindkey  "${key[Left]}"    backward-char
-[[ -n "${key[Right]}"   ]]  && bindkey  "${key[Right]}"   forward-char
+# function zkbd_file() {
+#     [[ -f ${ZDOTDIR}/.zkbd/${TERM}-${VENDOR}-${OSTYPE} ]] && printf '%s' ${ZDOTDIR}/".zkbd/${TERM}-${VENDOR}-${OSTYPE}" && return 0
+#     [[ -f ${ZDOTDIR}/.zkbd/${TERM}-${DISPLAY}          ]] && printf '%s' ${ZDOTDIR}/".zkbd/${TERM}-${DISPLAY}"          && return 0
+#     return 1
+# }
 
-[[ -n "${key[PageUp]}"   ]]  && bindkey  "${key[PageUp]}"   history-search-backward
-[[ -n "${key[PageDown]}"   ]]  && bindkey  "${key[PageDown]}"   history-search-forward
+# [[ ! -d ${ZDOTDIR}/.zkbd ]] && mkdir ${ZDOTDIR}/.zkbd
+# keyfile=$(zkbd_file)
+# ret=$?
+# if [[ ${ret} -ne 0 ]]; then
+#     zkbd
+#     keyfile=$(zkbd_file)
+#     ret=$?
+# fi
+# if [[ ${ret} -eq 0 ]] ; then
+#     source "${keyfile}"
+# else
+#     printf 'Failed to setup keys using zkbd.\n'
+# fi
+# unfunction zkbd_file; unset keyfile ret
+
+# setup keys
+[[ -n "${key[Home]}"     ]] && bindkey "${key[Home]}"     beginning-of-line
+[[ -n "${key[End]}"      ]] && bindkey "${key[End]}"      end-of-line
+[[ -n "${key[Insert]}"   ]] && bindkey "${key[Insert]}"   overwrite-mode
+[[ -n "${key[Delete]}"   ]] && bindkey "${key[Delete]}"   delete-char
+[[ -n "${key[Up]}"       ]] && bindkey "${key[Up]}"       up-line-or-history
+[[ -n "${key[Down]}"     ]] && bindkey "${key[Down]}"     down-line-or-history
+[[ -n "${key[Left]}"     ]] && bindkey "${key[Left]}"     backward-char
+[[ -n "${key[Right]}"    ]] && bindkey "${key[Right]}"    forward-char
+[[ -n "${key[PageUp]}"   ]] && bindkey "${key[PageUp]}"   history-search-backward
+[[ -n "${key[PageDown]}" ]] && bindkey "${key[PageDown]}" history-search-forward
+[[ -n "${key[C-Left]}"   ]] && bindkey "${key[C-Left]}"   backward-word
+[[ -n "${key[C-Right]}"  ]] && bindkey "${key[C-Right]}"  forward-word
+
+[[ -n "${key[Home]}"     ]] && bindkey -M vicmd "${key[Home]}"    beginning-of-line
+[[ -n "${key[End]}"      ]] && bindkey -M vicmd "${key[End]}"     end-of-line
 
 bindkey -M vicmd '^R' redo
 bindkey -M vicmd 'u'  undo
@@ -49,3 +58,4 @@ bindkey '^X^I' expand-or-complete-prefix
 bindkey '^X^H' expand-history
 
 bindkey '^o' accept-and-infer-next-history
+
